# Istio mTLS Strict Mode Configuration
# Applies Zero Trust principle: All service-to-service communication must be encrypted

# 1. Mesh-wide strict mTLS policy
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: default
  namespace: istio-system
spec:
  mtls:
    mode: STRICT
---
# 2. Demo namespace strict mTLS
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: demo-mtls
  namespace: demo
spec:
  mtls:
    mode: STRICT
---
# 3. Destination rule for mTLS enforcement
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: demo-app-mtls
  namespace: demo
spec:
  host: demo-app.demo.svc.cluster.local
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: keycloak-mtls
  namespace: demo
spec:
  host: keycloak.demo.svc.cluster.local
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: oauth2-proxy-mtls
  namespace: demo
spec:
  host: oauth2-proxy.demo.svc.cluster.local
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
---
# 4. Network Policy for Zero Trust microsegmentation
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: deny-all
  namespace: demo
spec:
  podSelector: {}
  policyTypes:
    - Ingress
    - Egress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-demo-app
  namespace: demo
spec:
  podSelector:
    matchLabels:
      app: demo-app
  policyTypes:
    - Ingress
    - Egress
  ingress:
    # Allow from oauth2-proxy
    - from:
        - podSelector:
            matchLabels:
              app: oauth2-proxy
      ports:
        - protocol: TCP
          port: 8000
    # Allow from Istio ingress gateway
    - from:
        - namespaceSelector:
            matchLabels:
              name: istio-system
      ports:
        - protocol: TCP
          port: 8000
  egress:
    # Allow DNS
    - to:
        - namespaceSelector: {}
      ports:
        - protocol: UDP
          port: 53
    # Allow to Keycloak for token validation
    - to:
        - podSelector:
            matchLabels:
              app: keycloak
      ports:
        - protocol: TCP
          port: 8080
    # Allow to AWS microservice (WireGuard network)
    - to:
        - ipBlock:
            cidr: 10.10.0.0/24  # WireGuard network
      ports:
        - protocol: TCP
          port: 8080
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-oauth2-proxy
  namespace: demo
spec:
  podSelector:
    matchLabels:
      app: oauth2-proxy
  policyTypes:
    - Ingress
    - Egress
  ingress:
    # Allow from Istio ingress gateway
    - from:
        - namespaceSelector:
            matchLabels:
              name: istio-system
      ports:
        - protocol: TCP
          port: 4180
  egress:
    # Allow DNS
    - to:
        - namespaceSelector: {}
      ports:
        - protocol: UDP
          port: 53
    # Allow to Keycloak
    - to:
        - podSelector:
            matchLabels:
              app: keycloak
      ports:
        - protocol: TCP
          port: 8080
    # Allow to demo-app
    - to:
        - podSelector:
            matchLabels:
              app: demo-app
      ports:
        - protocol: TCP
          port: 8000
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-keycloak
  namespace: demo
spec:
  podSelector:
    matchLabels:
      app: keycloak
  policyTypes:
    - Ingress
    - Egress
  ingress:
    # Allow from oauth2-proxy
    - from:
        - podSelector:
            matchLabels:
              app: oauth2-proxy
      ports:
        - protocol: TCP
          port: 8080
    # Allow from demo-app
    - from:
        - podSelector:
            matchLabels:
              app: demo-app
      ports:
        - protocol: TCP
          port: 8080
    # Allow from Istio ingress gateway (for login page)
    - from:
        - namespaceSelector:
            matchLabels:
              name: istio-system
      ports:
        - protocol: TCP
          port: 8080
  egress:
    # Allow DNS
    - to:
        - namespaceSelector: {}
      ports:
        - protocol: UDP
          port: 53
