# Network Policies cho Zero Trust - Fixed version
# Cho phép traffic từ Istio ingress gateway

apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-istio-ingress
  namespace: demo
spec:
  podSelector: {}
  policyTypes:
    - Ingress
  ingress:
    # Allow all ingress from istio-system (ingress gateway)
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: istio-system
    # Allow pod-to-pod in same namespace
    - from:
        - podSelector: {}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-egress
  namespace: demo
spec:
  podSelector: {}
  policyTypes:
    - Egress
  egress:
    # Allow DNS
    - to:
        - namespaceSelector: {}
      ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53
    # Allow all egress to same namespace
    - to:
        - podSelector: {}
    # Allow egress to istio-system
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: istio-system
    # Allow external HTTPS (for nip.io DNS, etc)
    - to:
        - ipBlock:
            cidr: 0.0.0.0/0
      ports:
        - protocol: TCP
          port: 443
        - protocol: TCP
          port: 80
